// Generates typed ABI modules from Foundry build artifacts (run `forge build` in packages/contracts first).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "../../contracts/out");
const targets = [
  ["EscrowCoreV4.sol/EscrowCoreV4.json", "escrowCoreV4Abi", "escrowCoreV4.ts"],
  ["LicensedArbitratorAdapter.sol/LicensedArbitratorAdapter.json", "licensedArbitratorAdapterAbi", "licensedArbitratorAdapter.ts"],
];

for (const [artifact, name, file] of targets) {
  const { abi } = JSON.parse(readFileSync(join(out, artifact), "utf8"));
  const body = `// Generated by scripts/gen-abi.mjs from ${artifact}. Do not edit.\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(here, "../src/abi", file), body);
  console.log(`wrote src/abi/${file} (${abi.length} entries)`);
}
